### ISSUE TITLE
Feature request: output mixing ratio of input coordinates, instead of the point's actual position

### ISSUE THREAD

**Issue by be5invis** [fontello/cubic2quad#3]
Given that OpenType has VF now, the source curve may not be eight numbers, but eight covectors that “respond” to a style selector to make the font able to provide infinite styles.
So that c2q may need some improvement that works for this situation: instead of outputing the actual coordinates of the given input curve, instead the mixing weights of coordinates of the input. i.e., originally:

```js
cubic2quad(xa, ya, xb, yb, xc, yc, xd, yd) -> [x1, y1, x2, y2, ...]
```

Now:
```js
cubic2quad(xa, ya, xb, yb, xc, yc, xd, yd) -> [[x1a, x1b, x1c, x1d], [y1a, y1b, y1c, y1d], ...]
where
x1a*xa + x1b*xb + x1c*xc + x1d*xd === x1
y1a*ya + y1b*yb + y1c*yc + y1d*yd === y1
...
```

**Comment by puzrin** [comment]
I suspect, this can be organized via wrappers. This package solves a simple math task, not depending on font internals.

May be i don't understand something, need more info then.

**Comment by be5invis** [comment]
@puzrin I am not going to depend on font internals. Simply, replace the result's X or Y into `[a, b, c, d]`.
For the simplest situation (one quadratic segment), the coefficients are:

```
point 1 : [1, 0, 0, 0]
point 2 : [(yc * xd - xc * yd) / k, (xc * yd - yc * xd) / k, (xa * yb - ya * xb) / k, (ya * xb - xa * yb) / k]
point 3 : [0, 0, 0, 1]
```

**Comment by puzrin** [comment]
Current api is clear and simple. I can not understand reasons for such change. Why do you request it instead of doing transforms before/after call at your side?

**Comment by be5invis** [comment]
@puzrin it is hard to exaplain though...
VF requires the outline in each "master" being compatible, so we cannot simply convert the cubic masters into quadratic.

**Comment by puzrin** [comment]
May be you need solution for a bit different math problem (similar, but not the same)? I'm not strong in this math. My goal is to understand, is it in scope of this package or not. Because we need to keep things simple.

That's like difference between 2D and 3D transforms - those are similar, but 2D library is good itself and should not do 3D jobs.

**Comment by puzrin** [comment]
Close - rejected.
